#pragma once
#include "config_common.h"

#define MATRIX_ROWS 4
#define MATRIX_COLS 14

#define MATRIX_ROW_PINS { GP14, GP23, GP24, GP25 }
#define MATRIX_COL_PINS { GP17, GP16, GP0, GP1, GP2, GP3, GP4, GP5, GP8, GP9, GP10, NO_PIN, NO_PIN, NO_PIN }

#define DIODE_DIRECTION COL2ROW
#define USB_POLLING_INTERVAL_MS 1
#define TAPPING_TERM 200
