MCU = RP2040
BOOTLOADER = rp2040

VIA_ENABLE = yes
NKRO_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no

VIAL_ENABLE ?= no

ifeq ($(VIAL_ENABLE), yes)
  VIA_ENABLE = yes
  OPT_DEFS += -DVIAL_ENABLE
endif
